
ALTER TABLE cards
DROP COLUMN tg,
DROP COLUMN whatsapp,
DROP COLUMN max,
DROP COLUMN facebook,
DROP COLUMN odnok,
DROP COLUMN mailru,
DROP COLUMN gmail,
DROP COLUMN yandex,
DROP COLUMN vk,
DROP COLUMN avito,
DROP COLUMN hh_ru,
DROP COLUMN ozon,
DROP COLUMN wb;