ALTER TABLE cards
ADD COLUMN tg BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN whatsapp BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN max BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN facebook BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN odnok BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN mailru BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN gmail BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN yandex BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN vk BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN avito BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN hh_ru BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN ozon BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN wb BOOLEAN NOT NULL DEFAULT false